language: generic 
sudo: required
services: docker

before_install:
  - docker build -t christophergrigg/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true christophergrigg/udemy-docker-react npm run test